name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN : ${{ secrets.GH_ACCESS_TOKEN }}
      GOPRIVATE: github.com/snowpackdata/cronos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com/snowpackdata".insteadOf "https://github.com/snowpackdata"
      # Recompile output.css for UI changes
      - name: tailwindcss - update output.css
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: static/css/main.css
          output: static/css/outputs.css
          params: "--minify"
      # Build the Go application
      - name: Go Get
        run: go get .
      - name: Build
        run: go build -v ./...
      # Create environment variable of current Git hash
      - name: Generate Commit Hash
        id: commit-hash
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_CREDENTIALS }}'
      - name: 'Deploy to GAE'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          build_env_vars: |-
              GOPRIVATE=github.com/snowpackdata/cronos
              GIT_HASH=${{ env.GIT_HASH }}
          env_vars: |-
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            CLOUD_SQL_CONNECTION_NAME=${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
            CLOUD_SQL_USERNAME=${{ secrets.CLOUD_SQL_USERNAME }}
            CLOUD_SQL_PASSWORD=${{ secrets.CLOUD_SQL_PASSWORD }}
            CLOUD_SQL_DATABASE_NAME=${{ secrets.CLOUD_SQL_DATABASE_NAME }}
            GCP_PROJECT=${{ secrets.GCP_PROJECT }}
            GCS_BUCKET=${{ secrets.GCS_BUCKET }}
            GIT_HASH=${{ env.GIT_HASH }}
            HUBSPOT_API_KEY=${{ secrets.HUBSPOT_API_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
            ENVIRONMENT=production
