name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/snowpackdata/cronos
      GH_ACCESS_TOKEN : ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com/snowpackdata".insteadOf "https://github.com/snowpackdata"
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_CREDENTIALS }}'
      - name: Update Google Cloud SDK
        run: sudo apt-get update && sudo apt-get --only-upgrade install google-cloud-sdk-app-engine-grpc google-cloud-sdk-cloud-build-local google-cloud-sdk-log-streaming google-cloud-sdk-kubectl-oidc google-cloud-sdk-pubsub-emulator google-cloud-sdk google-cloud-sdk-package-go-module google-cloud-sdk-app-engine-go
      - name: 'Deploy to GAE'
        uses: 'google-github-actions/deploy-appengine@v1'
