name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_CREDENTIALS }}'

      - name: 'Deploy to GAE'
        uses: 'google-github-actions/deploy-appengine@v1'
