name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/snowpackdata/cronos
      GH_ACCESS_TOKEN : ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/cronos.insteadOf https://github.com/cronos
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_CREDENTIALS }}'

      - name: 'Deploy to GAE'
        uses: 'google-github-actions/deploy-appengine@v1'
