name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    env:
      GOPRIVATE: github.com/snowpackdata/cronos
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - run: git config --global url."https://${{ secrets.GH_ACCESS_TOKEN }}:x-oauth-basic@github.com/snowpackdata".insteadOf "https://github.com/snowpackdata"
    - name: Build
      run: go build -v ./...

